### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jansivans** [tokurgit/new-endpoints-task#4]
Hello. 
Thank you for your work.
Everything looks good to me.
The only thing I have noticed you have used immediately invoked async function `(async () =>{})();` inside third endpoint.
Of course it will work, but it could be done much easier - simply by adding `async`:
```js
app.post('/excel-sum', upload.single('file'), async (req, res) =>
```
Please `await` a response from our HR manager.
Have a good day!

**Comment by tokurgit** [comment]
Hello,

Thanks for the reply and for the comment,I will definitely check it out.

Looking forward to hearing from HR!

Kind regards,
Toms Kursīts
Mob.nr. 25227875

**Comment by jansivans** [comment]
Great, thank you!
